import Reveal from './Reveal'
import SectionHeading from './SectionHeading'
import { ActivityIcon, TrendingUpIcon, MessageIcon, RocketIcon, CheckIcon } from '../lib/icons'

const management=[['01','Daily Operations','We handle recurring Amazon tasks and monitor the areas of your account that require attention.'],['02','Continuous Optimization','Listings, advertising, keywords, competitors, and performance are continuously reviewed for improvement opportunities.'],['03','Clear Communication','Stay informed about what we’re working on, what needs attention, and what comes next.'],['04','Built to Scale','Our support can grow alongside your catalog, advertising activity, sales, and operational requirements.']]
const audiences=[['New Sellers','Starting on Amazon?','We support the journey from market research and sourcing through listings, launch preparation, and ongoing management.'],['Growing Sellers','Ready for the next stage?','Strengthen listings, PPC, inventory planning, Seller Central operations, and overall marketplace performance.'],['Established Brands','Managing a larger Amazon presence?','Extend your team with marketplace operations, optimization, advertising, reporting, and account management.'],['Agencies & Teams','Need additional Amazon expertise?','OPVARO supports internal teams and agencies with ongoing Amazon operations and specialized marketplace work.']]
const benefits=[['Complete Amazon Expertise','From research and listings to PPC, FBA, inventory, and account operations.'],['Connected Management','We look at your Amazon business as a whole rather than treating every task separately.'],['Data-Led Decisions','Marketplace data, keywords, competitors, and performance insights guide our approach.'],['Flexible Support','Work with OPVARO for specific Amazon services or broader ongoing management.'],['Clear Reporting','Stay informed about completed work, performance, priorities, and next steps.']]
const capabilities=['Product Research','Market Research','Competitor Research','Product Sourcing','Supplier Research','Keyword Research','Listing Creation','Listing Optimization','Amazon SEO','PPC Management','Campaign Optimization','Seller Central Management','FBA Management','Inventory Management','Shipment Support','Catalog Management','Variation Management','Account Health','Case Management','Appeal Support','A+ Content','Brand Store','Customer Support','Sales Reporting','Performance Analysis','Ongoing Account Management']

export function Management(){return <section className="bg-paper py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading dark eyebrow="End-to-End Management" title="More Than Tasks. We Manage the Bigger Picture." subtext="Amazon success depends on connected moving parts. Listings affect advertising. Advertising affects sales. Sales affect inventory. Inventory affects rankings. OPVARO manages these areas together."/><div className="grid md:grid-cols-2">{management.map(([n,t,b],i)=><Reveal key={t} delay={i*70}><article className={`h-full border-b border-mist py-8 md:px-8 ${i%2===0?'md:border-r md:pl-0':'md:pr-0'}`}><p className="font-display text-5xl font-medium text-[#b99aff]">{n}</p><h3 className="mt-4 text-xl font-semibold text-deep-iris">{t}</h3><p className="mt-3 max-w-lg leading-relaxed text-slate">{b}</p></article></Reveal>)}</div></div></section>}

export function Audience(){return <section className="bg-white py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading dark eyebrow="Who We Work With" title="Built for Every Stage of Amazon Growth."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{audiences.map(([label,title,body],i)=><Reveal key={label} delay={i*70}><article className="h-full rounded-lg border border-mist bg-paper p-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-royal-amethyst">{label}</p><h3 className="mt-5 font-display text-2xl font-medium text-deep-iris">{title}</h3><p className="mt-3 text-sm leading-relaxed text-slate">{body}</p></article></Reveal>)}</div></div></section>}

export function WhyOpvaro(){const icons=[ActivityIcon,TrendingUpIcon,MessageIcon,RocketIcon,CheckIcon];return <section className="bg-paper py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading dark eyebrow="Why OPVARO" title="One Team Behind Your Amazon Business." subtext="Instead of coordinating different people for research, listings, advertising, inventory, and account operations, OPVARO brings Amazon management together in one place."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{benefits.map(([title,body],i)=>{const Icon=icons[i];return <Reveal key={title} delay={i*60}><article className="h-full rounded-lg border border-mist bg-white p-5"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-mist-violet"><Icon className="h-5 w-5 text-royal-amethyst"/></span><h3 className="mt-4 font-semibold text-deep-iris">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate">{body}</p></article></Reveal>})}</div></div></section>}

export function Capabilities(){return <section className="bg-white py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-6xl px-4 text-center sm:px-6"><Reveal><p className="text-xs font-bold uppercase tracking-[.16em] text-royal-amethyst">Our Capabilities</p><h2 className="mx-auto mt-4 max-w-3xl font-display text-4xl font-medium leading-none text-deep-iris sm:text-5xl">The Work Behind Your Amazon Business — Covered.</h2></Reveal><Reveal delay={100}><div className="mt-10 flex flex-wrap justify-center gap-2.5">{capabilities.map(item=><span key={item} className="rounded-full border border-mist bg-paper px-4 py-2 text-sm font-medium text-plum-velvet transition-colors hover:border-[#b99aff] hover:bg-mist-violet">{item}</span>)}</div></Reveal></div></section>}
