import Reveal from './Reveal'
import SectionHeading from './SectionHeading'
import CalendlyButton from './CalendlyButton'
import { SearchIcon, PackageIcon, FileTextIcon, TrendingUpIcon, MegaphoneIcon, ActivityIcon, BoxIcon, ShieldIcon, ClipboardIcon, StarIcon, MessageIcon, EyeIcon } from '../lib/icons'
const services = [
  [SearchIcon,'Product & Market Research','Identify promising opportunities through product, niche, competitor, demand, pricing, and market research.'],
  [PackageIcon,'Sourcing & Supplier Coordination','Support with supplier research, quotation comparison, cost analysis, product requirements, and sourcing coordination.'],
  [FileTextIcon,'Listing Creation & Optimization','Build clear, keyword-focused listings with optimized titles, bullets, descriptions, backend terms, and positioning.'],
  [TrendingUpIcon,'Amazon SEO & Keyword Strategy','Research relevant search terms, uncover keyword opportunities, analyze competitors, and improve organic visibility.'],
  [MegaphoneIcon,'PPC Advertising','Build, manage, and optimize campaigns through research, bidding, targeting, search-term analysis, and monitoring.'],
  [ActivityIcon,'Seller Central Management','Handle catalog updates, cases, orders, account monitoring, and recurring Seller Central tasks.'],
  [BoxIcon,'FBA & Inventory Management','Monitor inventory, FBA stock, shipments, replenishment requirements, and potential stock issues.'],
  [ShieldIcon,'Account Health & Compliance','Monitor account health, performance notifications, cases, policy issues, and assist with appeals when required.'],
  [ClipboardIcon,'Catalog & Variation Management','Manage product information, variations, parent-child structures, and catalog-related Seller Central issues.'],
  [StarIcon,'A+ Content & Brand Store','Plan and optimize A+ Content and Storefront experiences with stronger structure and product presentation.'],
  [MessageIcon,'Customer Experience','Support buyer communication, order concerns, returns, and service operations in line with marketplace policies.'],
  [EyeIcon,'Reporting & Growth Strategy','Monitor sales, advertising, listings, inventory, competitors, and performance to uncover opportunities.'],
]
export default function Services(){return <section id="services" className="relative overflow-hidden bg-white py-16 sm:py-20 lg:py-24"><div className="pointer-events-none absolute right-[-8%] top-24 h-[380px] w-[380px] rounded-full bg-[#b99aff]/20 blur-3xl"/><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><SectionHeading dark eyebrow="What We Manage" title="Complete Amazon Marketplace Services" subtext="From launch to daily operations and long-term growth, we support every major part of your Amazon business."/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map(([Icon,title,body],i)=><Reveal key={title} delay={(i%3)*70}><article className="group h-full rounded-lg border border-mist bg-paper p-5 transition-all hover:-translate-y-1 hover:bg-white hover:shadow-[0_16px_24px_-18px_rgba(38,17,74,.22)] sm:p-6"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-mist-violet"><Icon className="h-5 w-5 text-royal-amethyst"/></span><h3 className="mt-4 font-display text-xl font-medium leading-tight text-deep-iris">{title}</h3><p className="mt-3 text-sm leading-relaxed text-slate">{body}</p></article></Reveal>)}</div><Reveal><div className="mt-8 flex flex-col gap-5 rounded-lg border border-mist bg-[linear-gradient(135deg,#f7f5ff,#edecff_60%,#fff)] p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"><div><h3 className="font-display text-2xl font-medium text-deep-iris">Need complete Amazon management?</h3><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate">From daily operations to ongoing optimization, OPVARO can manage the areas of your Amazon business that need consistent attention.</p></div><CalendlyButton className="shrink-0">Let&apos;s Talk</CalendlyButton></div></Reveal></div></section>}
