import { useState } from 'react'
import Reveal from './Reveal'
import { ChevronDownIcon } from '../lib/icons'

const faqs=[
  ['What Amazon services does OPVARO provide?','OPVARO supports Amazon businesses across product research, sourcing, listings, SEO, PPC advertising, Seller Central operations, FBA, inventory, catalog management, account health, customer support, reporting, and ongoing marketplace management.'],
  ['Can OPVARO manage my complete Amazon operation?','Yes. OPVARO can support multiple areas of your Amazon business under one coordinated workflow, or focus on specific services based on your requirements.'],
  ['Can I work with OPVARO for only one service?','Yes. You can work with us for individual services such as product research, listing optimization, PPC management, catalog work, or Seller Central support.'],
  ['Do you work with new Amazon sellers?','Yes. We can assist new sellers from the early research and preparation stages through launch and ongoing marketplace operations.'],
  ['Do you work with established Amazon brands?','Yes. OPVARO can support existing brands with ongoing management, advertising, optimization, inventory, reporting, catalog operations, and other Amazon marketplace requirements.'],
  ['Do you manage Amazon PPC?','Yes. PPC support can include campaign setup, keyword research, targeting, bid optimization, search-term analysis, negative targeting, monitoring, and ongoing optimization.'],
  ['How do I get started?','Contact OPVARO and tell us about your Amazon business, current challenges, and the support you need. We’ll review your requirements and determine the right way to work together.']
]

export default function Trust(){return <section id="faq" className="relative overflow-hidden bg-paper py-16 sm:py-20 lg:py-24"><div className="pointer-events-none absolute -right-32 top-20 h-80 w-80 rounded-full bg-[#b99aff]/20 blur-3xl"/><div className="relative mx-auto max-w-5xl px-4 sm:px-6"><Reveal><div className="text-center"><p className="inline-flex rounded-full bg-mist-violet px-3 py-1.5 text-xs font-semibold uppercase tracking-[.12em] text-royal-amethyst">Questions, answered</p><h2 className="mt-5 font-display text-4xl font-medium leading-none text-deep-iris sm:text-5xl">Frequently Asked Questions</h2><p className="mx-auto mt-4 max-w-2xl leading-relaxed text-slate">Clear answers about how OPVARO supports Amazon sellers, brands, and marketplace teams.</p></div></Reveal><div className="mt-10 grid gap-3">{faqs.map(([q,a],i)=><Reveal key={q} delay={Math.min(i*55,275)}><FaqItem number={i+1} question={q} answer={a} defaultOpen={i===0}/></Reveal>)}</div></div></section>}

function FaqItem({number,question,answer,defaultOpen}){const[open,setOpen]=useState(defaultOpen);return <article className={`group overflow-hidden rounded-xl border bg-white transition-all duration-300 ${open?'border-[#c9b3ff] shadow-[0_14px_35px_-24px_rgba(62,0,121,.42)]':'border-mist hover:-translate-y-0.5 hover:border-[#d8cbf5] hover:shadow-[0_12px_28px_-24px_rgba(62,0,121,.30)]'}`}><button type="button" className="flex w-full items-center gap-4 px-4 py-4 text-left sm:px-6 sm:py-5" aria-expanded={open} onClick={()=>setOpen(!open)}><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-bold transition-colors duration-300 ${open?'bg-royal-amethyst text-white':'bg-mist-violet text-royal-amethyst'}`}>{String(number).padStart(2,'0')}</span><span className="flex-1 font-semibold text-deep-iris sm:text-base">{question}</span><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full transition-all duration-300 ${open?'rotate-180 bg-royal-amethyst text-white':'bg-paper text-royal-amethyst group-hover:bg-mist-violet'}`}><ChevronDownIcon className="h-4 w-4"/></span></button><div className={`grid transition-[grid-template-rows] duration-500 ease-[cubic-bezier(.22,1,.36,1)] ${open?'grid-rows-[1fr]':'grid-rows-[0fr]'}`}><div className="overflow-hidden"><p className={`border-t px-4 pb-6 pt-5 text-sm leading-7 text-slate transition-all duration-500 sm:ml-[4.5rem] sm:px-0 sm:pr-16 ${open?'translate-y-0 border-mist opacity-100':'-translate-y-2 border-transparent opacity-0'}`}>{answer}</p></div></div></article>}
