import { Link } from 'react-router-dom'
import Logo from '../Logo'
import CalendlyButton from '../CalendlyButton'
import { CONTACT_EMAIL } from '../../lib/constants'
import { LinkedinIcon, XTwitterIcon } from '../../lib/icons'
const quick=[['Home','/#home'],['Services','/#services'],['How It Works','/#process'],['About Us','/#about'],['FAQs','/#faq'],['Contact','/#contact']]
const services=[['Product Research','/#services'],['Listing Optimization','/#services'],['Amazon SEO','/#services'],['PPC Management','/#services'],['Seller Central','/#services'],['FBA & Inventory','/#services'],['Account Health','/#services'],['Account Management','/#services']]
function Tape({className=''}){return <svg className={className} viewBox="0 0 95 80" fill="none" aria-hidden="true"><path d="M1 45 70.3 5l18 31.2L19 76.2 1 45Z" fill="#26114a"/><path d="m9 46 61-35 3 5-61 35-3-5Zm8 14 61-35 3 5-61 35-3-5Z" fill="#fff" opacity=".09"/></svg>}
function Column({title,items}){return <div><h3 className="text-xs font-semibold uppercase tracking-[.14em] text-ash">{title}</h3><ul className="mt-4 grid gap-2.5">{items.map(([l,h])=><li key={l}><Link to={h} className="text-sm font-medium text-slate hover:text-royal-amethyst">{l}</Link></li>)}</ul></div>}
export function TapedFooter(){return <footer className="border-t border-mist bg-[#f1eff6] px-4 py-8 text-plum-velvet sm:px-6 sm:py-10"><div className="relative mx-auto max-w-[1200px] rounded-3xl border border-white/80 bg-white px-5 py-10 shadow-[0_20px_50px_rgba(38,17,74,.10)] sm:px-8 lg:px-12"><Tape className="absolute -left-7 -top-5 hidden h-16 w-20 -rotate-3 md:block"/><Tape className="absolute -right-7 -top-5 hidden h-16 w-20 rotate-[87deg] md:block"/><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-[1.3fr_.65fr_.8fr_.8fr]"><div><Logo/><p className="mt-3 text-sm font-semibold text-deep-iris">Amazon Marketplace Management &amp; Growth</p><p className="mt-3 max-w-sm text-sm leading-relaxed text-slate">We help sellers and brands manage the work behind their Amazon business — from research and listings to advertising, inventory, Seller Central, and ongoing marketplace operations.</p><a href={`mailto:${CONTACT_EMAIL}`} className="mt-4 inline-flex text-sm font-semibold text-royal-amethyst">{CONTACT_EMAIL}</a></div><Column title="Quick Links" items={quick}/><Column title="Services" items={services}/><div><h3 className="text-xs font-semibold uppercase tracking-[.14em] text-ash">Need help with Amazon?</h3><p className="mt-4 text-lg font-semibold text-deep-iris">Let&apos;s build the right support plan.</p><CalendlyButton className="mt-5 w-full">Let&apos;s Talk →</CalendlyButton><div className="mt-5 flex gap-2"><a href="https://www.linkedin.com/company/opvaro" aria-label="LinkedIn" className="flex h-9 w-9 items-center justify-center rounded-full bg-mist-violet"><LinkedinIcon className="h-4 w-4"/></a><a href="https://x.com/opvaro" aria-label="X" className="flex h-9 w-9 items-center justify-center rounded-full bg-mist-violet"><XTwitterIcon className="h-4 w-4"/></a></div></div></div></div><div className="mx-auto mt-5 flex max-w-[1200px] flex-col gap-3 text-xs text-ash sm:flex-row sm:justify-between"><p>© 2026 OPVARO. All rights reserved.</p><div className="flex gap-5"><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms &amp; Conditions</Link></div></div></footer>}
